name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [16.14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Linter
        run: npm i
      - name: Build
        run: npm run build
      - name: Create packet
        run: npm run pack
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tcore"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
