name: Multi-Arch Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64/v8, linux/arm/v7, linux/ppc64le, linux/s390x]
        include:
          - platform: linux/amd64
          - platform: linux/arm64/v8
          - platform: linux/arm/v7
          - platform: linux/ppc64le
          - platform: linux/s390x

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=local,dest=./output/${{ matrix.platform }}
