name: Multi-Arch Docker Build and Push

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: matrix.platform == 'linux/amd64'  # Login only once
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Tags
        id: tags
        run: |
          echo "DOCKER_IMAGE=tagoio/tagocore" >> $GITHUB_ENV
          if [[ ${{ github.ref_name }} == *"-beta"* ]]; then
            echo "TAG=beta" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${DOCKER_IMAGE}:${GITHUB_REF_NAME}
            ${DOCKER_IMAGE}:${{ env.TAG }}
          build-args:
            BUILD_PLATFORM=${{ matrix.platform }}
