name: Publish Docker image

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Tags
        id: tags
        run: |
          echo "DOCKER_IMAGE=tagoio/tagocore" >> $GITHUB_ENV
          echo "GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/tagocore" >> $GITHUB_ENV
          if [[ ${{ github.ref_name }} == *"-beta"* ]]; then
            echo "TAG=beta" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
            ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
            ${{ env.GHCR_IMAGE }}:${{ github.ref_name }}
            ${{ env.GHCR_IMAGE }}:${{ env.TAG }}
