name: Code Quality

on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t server-${{ github.sha }} .
        docker save -o server-${{ github.sha }}.tar server-${{ github.sha }}

    - name: Cache Docker Image
      uses: actions/cache@v4
      with:
        path: server-${{ github.sha }}.tar
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

  linter:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Restore Docker Image Cache
      uses: actions/cache@v4
      with:
        path: server-${{ github.sha }}.tar
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Load Docker Image
      run: docker load -i server-${{ github.sha }}.tar

    - name: Run Linter
      run: docker run server-${{ github.sha }} linter

  tests:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Restore Docker Image Cache
      uses: actions/cache@v4
      with:
        path: server-${{ github.sha }}.tar
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Load Docker Image
      run: docker load -i server-${{ github.sha }}.tar

    - name: Run Tests
      run: docker run server-${{ github.sha }} test
